In [1]:
import pandas as pd
import numpy as np

# Check NumPy version
print(np.__version__)

# Create array of zeros
print(np.zeros(5))

2.3.1
[0. 0. 0. 0. 0.]


In [ ]:
np.zeros(5)

In [ ]:
np.ones(5)

In [ ]:
a= np.array([1,2,2,3,5,7,12])   
a

In [ ]:
a[2]=122
a[2]
a


In [ ]:
np.arange(10, 20)

In [ ]:
np.linspace(0,1,11)


In [ ]:
#multi-dimensional arrays
np.zeros((3,4))


In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
np.random.seed(2)
100*np.random.rand(5, 2)

In [ ]:
a=np.arange(5)
a


In [ ]:
a+1

In [ ]:
b = (10+(a*2)**2)/100
b

In [ ]:
a+b

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
a>=2

array([False, False,  True,  True,  True])

In [37]:
a>b

array([False,  True,  True,  True,  True])

In [38]:
a.max()

np.int64(4)

In [40]:
a.min()

np.int64(0)

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
 
df= pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [4]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [10]:
#df.Engine Cylinders
df['Engine Cylinders']#

0    4
1    4
2    4
3    4
4    6
Name: Engine Cylinders, dtype: int64

In [17]:
#making a new column
df['id'] = [1,2,3,4,5]  
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [18]:
#deleting a column
del df['id']



In [20]:
df.index


RangeIndex(start=0, stop=5, step=1)

In [5]:
#accessing elements by position
df.loc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [6]:
#setting new index
df.index = ['a','b','c','d','e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [ ]:
# Find number of records in the DataFrame
print(f"Number of records: {len(df)}")


Number of records: 9704
DataFrame shape (rows, columns): (9704, 11)
Total records: 9704
Total columns: 11


In [33]:

fuel_types = df['fuel_type'].nunique()

print(f"Number of unique fuel types: {fuel_types}")

Number of unique fuel types: 2


In [ ]:
missing_values = df.isnull().sum()
print(missing_values)



Missing values per column:
engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [23]:
df.groupby('fuel_efficiency_mpg').max()

engine_displacement  num_cylinders  horsepower  \
fuel_efficiency_mpg                                                   
6.200971                              90            3.0       174.0   
6.676475                             220            0.0       132.0   
6.695483                             160            1.0       166.0   
6.762991                             220            4.0       144.0   
6.805975                             130            1.0       165.0   
...                                  ...            ...         ...   
23.369176                            140            2.0       113.0   
23.556075                            240            5.0       151.0   
23.759123                            330            3.0       136.0   
24.971452                            180            2.0       188.0   
25.967222                            210            3.0       206.0   

                     vehicle_weight  acceleration  model_year  origin  \
fuel_efficiency_mpg                                                     
6.200971                4726.977269          16.5        2020  Europe   
6.676475                4643.568672          15.2        2020  Europe   
6.695483                4604.494580          16.4        2007     USA   
6.762991                4527.955273          21.9        2023  Europe   
6.805975                4739.077089           NaN        2008     USA   
...                             ...           ...         ...     ...   
23.369176               1336.444231          16.2        2015  Europe   
23.556075               1314.839625          15.0        2012     USA   
23.759123               1223.298226           NaN        2001    Asia   
24.971452               1066.328301           NaN        2013     USA   
25.967222                952.681761          18.5        2015  Europe   

                    fuel_type         drivetrain  num_doors  
fuel_efficiency_mpg                                          
6.200971               Diesel  Front-wheel drive        1.0  
6.676475               Diesel    All-wheel drive        1.0  
6.695483               Diesel    All-wheel drive        0.0  
6.762991             Gasoline    All-wheel drive       -1.0  
6.805975               Diesel    All-wheel drive       -1.0  
...                       ...                ...        ...  
23.369176              Diesel  Front-wheel drive        1.0  
23.556075            Gasoline  Front-wheel drive        0.0  
23.759123            Gasoline  Front-wheel drive        1.0  
24.971452            Gasoline  Front-wheel drive        2.0  
25.967222            Gasoline  Front-wheel drive       -1.0  

[9704 rows x 10 columns]

In [25]:
df['horsepower'].median()

np.float64(149.0)

In [29]:
df['vehicle_weight'].sum()


np.float64(29124430.759692907)